[workspace]
resolver = "3"

members = [
    "testApp", "testMessageParserApp",
    "usb"
]

[workspace.package]
version = "0.1.0"
edition = "2024"

license = "MIT"
authors = [
    "Malte Linke <me@parzival.space>"
]

repository = "https://github.com/parzival-space/rodecaster-utility"

[workspace.dependencies]
log = "0.4.29"
thiserror = "2.0.18"
anyhow = "1.0.102"

# todo: remove tokio
tokio = "1.50.0"
crossbeam = "0.8.4"

# usb stuff
byteorder = "1.5.0"
hidapi = { version = "2.6.5", features = ["linux-static-hidraw"] }
