[workspace]
resolver = "3"
members = ["app","cli","usb"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-2 AND GPL-3"
authors = [
    "Malte Linke <me@parzival.space>"
]

repository = "https://github.com/parzival-space/rodecaster-utility"

[workspace.dependencies]
# logging
log = "0.4.32"
simplelog = "0.12.2"

# error handling
thiserror = "2.0.18"
anyhow = "1.0.102"

clap = "4.6.1"

serde = "1.0.228"
serde_json = "1.0.150"

crossbeam = "0.8.4"

# usb stuff
byteorder = "1.5.0"
hidapi = { version = "2.6.6", features = ["linux-static-hidraw"] }
nom = "8.0.0"
