[package]
name = "rodecaster-utility"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
tauri = { version = "2.11.5", features = [ "config-json5" ] }

[build-dependencies]
tauri-build = { version = "2.6.3", features = [ "config-json5" ] }
