[package]
name = "rodecaster-usb"

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "download-pro-ii-state"
path = "src/bin/download_rodecaster_pro_ii_state.rs"

[dependencies]
log.workspace = true
thiserror.workspace = true

hidapi.workspace = true
byteorder.workspace = true
crossbeam.workspace = true
nom.workspace = true