[package]
name = "rodecaster-usb"

version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license = "GPL-2"

[dependencies]
log.workspace = true
thiserror.workspace = true

hidapi.workspace = true
byteorder.workspace = true
crossbeam.workspace = true
nom.workspace = true

# todo: remove serde and serde_json as they are currently only used in a test
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true