import { Button } from "std-widgets.slint";
import { IconDisplay, IconSet } from "@lucide";

export component MainWindow inherits Window {
    no-frame: true;

    width: 1202px;
    height: 722px;

    background: #212121;

    // flying titlebar button
    HorizontalLayout {
        padding-top: 22px;
        padding-left: 20px;
        spacing: 11px;

        DragArea {
            width: 100px;
            height: 100px;

        }

        IconDisplay {
            icon: IconSet.FilePlay;
            stroke: white;
            width: 26px;
            height: 26px;
        }
        Button {
            width: 26px;
            height: 26px;
        }

        Button {
            text: "S";
            width: 26px;
            height: 26px;
        }
    }

    HorizontalLayout {
        padding-top: 100px;

        VerticalLayout {
            Text {
                text: "RODECasterPro II";
                width: 310px;
                height: 100px;

            }
        }
    }
}