name: Mirror Repository
on: [push]

jobs:
  codeberg:
    name: Codeberg.org
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: '${{ secrets.CODEBERG_REMOTE }}'
          GIT_SSH_PRIVATE_KEY: ${{ secrets.CODEBERG_DEPLOY_KEY }}
          GIT_SSH_NO_VERIFY_HOST: "true"